### ISSUE TITLE
Tracking: Consent Proof (Protos)

### ISSUE THREAD

**Issue by alexrisch** [xmtp/proto#159]
### Context

Add Protos for Consent Proofs outlined in XIP-43 (SMALL)
https://community.xmtp.org/t/xip-43-consent-proofs/552

### Progress

This change is complete when it has been implemented in all our SDKs:
  - [x] [xmtp-js](https://github.com/xmtp/xmtp-js/issues/594)
  - [x] [xmtp-ios](https://github.com/xmtp/xmtp-ios/issues/309)
  - [x] [xmtp-android](https://github.com/xmtp/xmtp-android/issues/220)
  - [ ] [xmtp-react-native](https://github.com/xmtp/xmtp-react-native/issues/354)
  - [x] Update [PROTOCOL.md](https://github.com/xmtp/proto/blob/main/PROTOCOL.md)
