### ISSUE TITLE
Tracking: Update SDKs to de-dup conversations by conversationId

### ISSUE THREAD

**Issue by elisealix22** [xmtp/proto#70]
### Context

Developers are experiencing an issue where there are duplicate conversations for a single ConversationId. This leads to messages being lost as they are split into different topics.

The root cause is:

- If multiple conversations are started with the same participants/ConversationId in a short period of time, this results in multiple invites being sent.
- SDK currently treats every invite as a distinct Conversation and returns the duplicates to developers

### Solution

1. SDK/Keystore should generate new invites with deterministic parameters, such that multiple invites point to the same topicName and use the same topicKey.
    1. TopicName and TopicKey should be derived from the symmetric encryption key generated in the initial keyExchange. e.g. `TopicKey = hkdf(symmetric_aes_key)`, `TopicName = Encrypt(symmetric_aes_key, {participants, conversationId})`
2. `listConversations` should be updated to remove duplicate entries with the same conversationId.
    1. This ought to occur in the same page, which could be a simplifying assumption.
3. SDK must deterministically resolve which invite to use when sending new messages
    1. This ensures that all messages end up in the same place.
    2. Keystore should use the most recent invite to to maximize forward compatibility
4. Existing duplicates will still exist, and will not be addressed at the SDK level. This should be a finite set of messages which will be less and less relevant and time progresses.
    1. New conversations will be fixed by A and B
    2. Once stabilized DM participants will use the same Topic for new messages
    3. If really needed; Apps can merge ‘Conversations’ with the same ConverstationID.

Full recommendation can be found [in this RAPID](https://www.notion.so/xmtplabs/RAPID-Dedupe-conversations-via-Determinism-18735a19ed1140fcbf95c2ea801c5422).

### Progress

This change is complete when it has been implemented in all our SDKs:
  - [ ] `xmtp-js`: https://github.com/xmtp/xmtp-js/issues/316
  - [ ] `xmtp-ios`: https://github.com/xmtp/xmtp-ios/issues/86
  - [ ] `xmtp-android`: https://github.com/xmtp/xmtp-android/issues/60
  - [ ] `xmtp-flutter`: https://github.com/xmtp/xmtp-flutter/issues/62
  - [ ] Update [PROTOCOL.md](https://github.com/xmtp/proto/blob/main/PROTOCOL.md) if necessary
