### ISSUE TITLE
Tracking: Update SDKs to ...

### ISSUE THREAD

**Issue by Kaikookpk12** [xmtp/proto#98]
### Progress

This change is complete when it has been implemented in all our SDKs:
  - [x] [xmtp-js](https://github.com/xmtp/xmtp-js) Link to tracking issue
  - [x] [xmtp-ios](https://github.com/xmtp/xmtp-ios) Link to tracking issue
  - [x] [xmtp-android](https://github.com/xmtp/xmtp-android) Link to tracking issue
  - [x] [xmtp-flutter](https://github.com/xmtp/xmtp-flutter) Link to tracking issue
  - [x] Update [PROTOCOL.md](https://github.com/xmtp/proto/blob/main/PROTOCOL.md) if necessary

```[tasklist]
### Tasks
- [ ] https://github.com/xmtp/proto/pull/97
```
